
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv
  namespace: metrics
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: alertmanager-storage
  local:
    path: /opt/alertmanager
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rahrup2c.mylabserver.com #Your server name
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-pv-claim
  namespace: metrics
  labels:
    app: wordpress
spec:
  storageClassName: alertmanager-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
